### ISSUE TITLE
Replace LambDynamicLights with Shimmer

### ISSUE THREAD

**Issue by Felix14-v2** [skywardmc/additive#36]
[Shimmer](https://modrinth.com/mod/shimmer!) is a great project with a flexible configuration possibilities for users and devs, including **colored** dynamic lighting. And it already can work with Sodium 0.5 :)
Maybe give it a chance?

By the way, LambDynamicLights has been seen causing a huge performance drops on some devices, including mine. Here's an example:
https://discord.com/channels/977987490742935652/1125634282128408626/1125696662313111592

Demo from discord:
https://pomf2.lain.la/f/ca5t9oyd.mp4

**Comment by Gaming32** [comment]
Shimmer doesn't work on Quilt because the mod is returning `null` from a method that is supposed to be not-null, which somehow works on Fabric, but doesn't on Quilt (as it shouldn't).

**Comment by MenacingPerson** [comment]
And the shimmer dev has some... weird... opinions on when they should add quilt support. According to them, quilt will be supported when quilt removes the WIP banner from their front page

**Comment by Gaming32** [comment]
The weird thing is that the only place I found where it doesn't work is that they're returning null from a method that should never have null returned from it. It's sloppy code and it's breaking on Quilt because Quilt expects that code to be written properly.

**Comment by MenacingPerson** [comment]
Well, if they don't want to fix it then reporting it to the quilt devs will probably work

**Comment by Gaming32** [comment]
Yeah, Quilt could probably handle that a bit better (like mimicking Fabric), but honestly it's just luck at this point that that *doesn't* crash on Fabric.

**Comment by MenacingPerson** [comment]
Shimmer also has a lot more stuff than LDL, that doesn't fit under OF compat. I wonder how laggy it is on low-end PCs.

**Comment by Felix14-v2** [comment]
> I wonder how laggy it is on low-end PCs.

Still better than LDL, which is broken on 1.20 (see attached video)

**Comment by Gaming32** [comment]
At least LDL loads

**Comment by MenacingPerson** [comment]
> Still better than LDL, which is broken on 1.20 (see attached video)

But that's a bug, surely. I meant that generally it seems to be doing a lot more, and it might not fit for Additive especially with coloured lights and stuff.
