### ISSUE TITLE
[suggestion] Replace EmoNO with MacOS Input Fixes

### ISSUE THREAD

**Issue by Aces-and-Jacks** [skywardmc/additive#38]
MacOS Input Fixes does everything EmoNO does and more

**Comment by orionzleon** [comment]
No it's bad

**Comment by Aces-and-Jacks** [comment]
oh...how?

**Comment by orionzleon** [comment]
it has worse fps and adds input lag while emuno does less of that

**Comment by Aces-and-Jacks** [comment]
oh. Well I guess then performance wise it's worse but bug fix wise it's better

**Comment by Aces-and-Jacks** [comment]
And if someone didn't have a mac wouldn't the mod deactivate/not apply?

**Comment by orionzleon** [comment]
no, with emuno, the mod would do nothing for windows users
with macos input fixes, it will do something that causes input lag even on windows

**Comment by Aces-and-Jacks** [comment]
oh, well thanks for the information. I don't believe there's too much of a disadvantage performance wise but if it still gets rejected I'm ok with that

**Comment by intergrav** [comment]
Based on what @orionzleon said, MacOS Input Fixes doesn't seem to be a very good replacement for EmuNO in Additive. You can add the mod manually if you still want it though.

*(EmuNO is also made by my friend so I guess I do also have a slight bias towards it :p)*

**Comment by orionzleon** [comment]
@intergrav Since you said that EmuNO was made by your friend, can you ask him to upload EmuNO to Curseforge, please?
