### ISSUE TITLE
Swap capes for cosmetica

### ISSUE THREAD

**Issue by Meow-purr** [skywardmc/additive#41]
[Cosmetica](cosmetica.cc) is a mod that adds in addition to capes also hats and shulder buddies it also supports more cape servers than capes

**Comment by MenacingPerson** [comment]
I don't know about that one.

1. Cosmetica is slow to update. It hasn't updated to 1.20.2 yet, and previous updates were also pretty slow.
2. Are those shoulder buddies and hats etc really fitting to vanilla? I don't think so.

It's always possible to add it yourself. It's what I do (I use cosmetica btw).

**Comment by intergrav** [comment]
I feel that Cosmetica would be a bit out of scope for Additive - OptiFine does not provide cosmetic features other than capes (well other than the seasonal hats, but it's not a key feature of the mod) and I think that some of the cosmetics don't fit into Vanilla very well

**Comment by Meow-purr** [comment]
you can dissable all cosmetics other than capes and have support for more cape servers

**Comment by MenacingPerson** [comment]
> you can dissable all cosmetics other than capes and have support for more cape servers

Which ones are missing? If you do actually use one of them then you can ask the capes mod dev to add it
