### ISSUE TITLE
Modpack disables AltGr in Chat

### ISSUE THREAD

**Issue by Neon-44** [skywardmc/additive#46]
**Describe the bug**
any Characters that are written by pressing AltGr + a Key (such as @ or {} on a swssgerman Keyboard) can not be written in the chat / command-line

**To Reproduce**
1. have swissgerman keyboard layout (or any other that has Symbols that require AltGr)
2. open chat / command-line
3. try to input any character that needs AltGr Input
4. doesn't work

**Expected behavior**
It should output the @ or {}

**Screenshots**

**Device info (please complete the following information):**
 - OS: [Windows 11]
 - Minecraft version: [1.20.2]

**Additional context**
makes it virtually impossible to play with commands

**Comment by Neon-44** [comment]
Found the Problem. It's the "Fix Linux Keyboard" Mod

as an Ex-Linux User myself (and still a big Linux and FOSS fan, i just couldn't keep using it after reading opinions on it from actual cybersecurity experts) i kind of don't want to see this mod thrown out.
maybe we should put in a bug Report with the Mod itself? But then again i guess the Mod wasn't thought to be installed on Windows PCs at all anyways, so.....

**Comment by intergrav** [comment]
I think it would be a good idea to make an issue on the Fix Keyboard on Linux repository for this

**Comment by intergrav** [comment]
Saw that the issue has been fixed in a new release of the mod so I'll get to updating Additive when I have some more time
