### ISSUE TITLE
Add BetterF3 Mod

### ISSUE THREAD

**Issue by Rectos28** [skywardmc/additive#47]
Add BetterF3 Mod for a customizable F3 HUD
Mod's Link: https://modrinth.com/mod/betterf3

**Comment by notabirb1** [comment]
Not sure if this is the place to discuss, but I'd rather this mod wasn't added. In my experience, it causes a huge frame drop when opening the F3 menu.

**Comment by intergrav** [comment]
I don't think that BetterF3 really fits Additive's purpose as an OptiFine alternative, but you may install it manually if you wish
