### ISSUE TITLE
Remove 1.16.5 options.txt because there is no simulation distance in 1.16.5

### ISSUE THREAD

**Issue by Uranite** [skywardmc/additive#50]
**Is your request related to a problem? Please describe.**
As far as I'm aware, simulation distance doesn't exist in minecraft 1.16.5, so there is no use in having simulation distance set to 5 in options.txt

**Describe the solution you'd like**
Because the config for simulation distance is unused, and there are no other config inside options.txt, it'll be better to remove options.txt for version 1.16.5 altogether.

**Comment by intergrav** [comment]
This is no longer applicable as Additive no longer supports 1.16.5
