### ISSUE TITLE
Perhaps support `Zume` instead of Zoomify

### ISSUE THREAD

**Issue by MenacingPerson** [skywardmc/additive#51]
**Is your request related to a problem? Please describe if so.**
Replace the zoom mod with `Zume`

**Describe the mod you'd like to add, remove, or change**
Add [Zume](https://modrinth.com/mod/zume)
Remove Zoomify

**List alternative mods or solutions you've considered**
N/A

**Additional context**
`Zume` is lighter than other mods and has cross-version support.  That's really the only reason

**Comment by intergrav** [comment]
I think that Zoomify is a better fit for Additive - it's a lot more intuitive to users since it can be configured through mod menu and seems to have more features, along with warnings if, for example, the zoom key is conflicting with another key
