### ISSUE TITLE
Polytone for custom colors

### ISSUE THREAD

**Issue by MehVahdJukaar** [skywardmc/additive#53]
Polytone us available 1.18-1.20.4 and allows for otpifine custom colours as well as for a bunch more customisation features like biome effects, particle modifiers, biome variant textures, custom sounds and way more

**Comment by Uranite** [comment]
To additive maintainer: Wait for sodium 0.5.6 before adding this to additive
https://github.com/MehVahdJukaar/polytone/issues/7#issuecomment-1892830092

**Comment by MehVahdJukaar** [comment]
That issue is only relevant to custom colormaps. Each and every of all the mod resource pack features still work

**Comment by intergrav** [comment]
Should be added once I update, thanks!

**Comment by intergrav** [comment]
Will polytone support 1.19.4 or 1.20.2 at any point? It's completely understandable if not, I'm just saying this because Additive supports those versions. If not, I can probably just use Bismuth and Vanadium on those versions

**Comment by MehVahdJukaar** [comment]
No there's really no point in backporting to these intermediary snapshot versions (Mojang can call them how they want, they remain snapshots) as basically nobody uses them. I already backported to many old versions I usually wouldn't have tho like 1.18 just because of the nature of this mod but going over all the minor one would be just a waste of time

**Comment by intergrav** [comment]
Additive and Adrenaline are both dropping support for all versions other than current Sodium LTS (1.20.1 and 1.20.4) anyway, so this should no longer be an issue. This change was done after a discussion in the Discord server.

I'll test this mod with the modpack soon :)
