### ISSUE TITLE
Downgrade OptiGUI

### ISSUE THREAD

**Issue by Uranite** [skywardmc/additive#59]
**Is your request related to a problem? Please describe if so.**
Currently Additive is including OptiGUI version 2.3.0-alpha.2 which is an alpha version.

**Describe the mod you'd like to add, remove, or change**
Downgrade OptiGUI to version 2.1.7 which is a release version

**List alternative mods or solutions you've considered**
None

**Additional context**
![image](https://github.com/skywardmc/additive/assets/62639703/fb59817e-2947-442c-8a75-b985da920a61)

**Comment by intergrav** [comment]
Will do so next update, didn't notice this at first when I was updating the mods
