### ISSUE TITLE
Cubes Without Borders

### ISSUE THREAD

**Issue by Uranite** [skywardmc/additive#60]
**Is your request related to a problem? Please describe if so.**
Currently Additive is using Borderless Mining for its borderless fullscreen feature, however it's not easy to toggle as it requires the user to navigate to the mod menu and then search for borderless fullscreen, while you can toggle borderless fullscreen in the video settings with Cubes Without Borders.

**Describe the mod you'd like to add, remove, or change**
Replace Borderless Mining with Cubes Without Borders.

**List alternative mods or solutions you've considered**
None

**Additional context**
An additional context would be that Fabulously Optimized removed Borderless Mining in favor of Cubes Without Borders and that is how I've gotten to know this mod in the first place.

**Comment by intergrav** [comment]
Doesn’t borderless mining have a config setting to do this? I think I have it off by default

**Comment by intergrav** [comment]
after a quick look in the FO thread i think it’s reasonable to add this and replace borderless mining 👍
