### ISSUE TITLE
"Play World", "Share World", "Create World" button names are empty in the German localization

### ISSUE THREAD

**Issue by marlester-dev** [skywardmc/additive#64]
**Describe the bug**
In the singe-player worlds menu these 3 buttons don't have names when the German language is chosen.

**To Reproduce**
1. Go to Languages and choose German
2. Go to the singleplayer menu
3. Look at the buttons
4. See the bug

**Expected behavior**
Buttons should have their German names.

**Screenshots**
When English is chosen:
![en](https://github.com/skywardmc/additive/assets/77095872/e6c23509-00a4-44c7-893a-249352039ff9)
When German is chosen:
![de](https://github.com/skywardmc/additive/assets/77095872/970fd226-cd9a-4239-8a44-63277d7a4a5e)

**Device info (please complete the following information):**
 - OS: Windows 10
 - Minecraft version: 1.20.4

**Additional context**
Modpack version - 1.25.1+1.20.4.fabric

**Comment by intergrav** [comment]
Thanks, will be looking into this. Could you try disabling the Loqui mod and see if that fixes it?

**Comment by Gaming32** [comment]
Base World Host does not have German translations for these buttons, so the game falls back to English.

**Comment by Gaming32** [comment]
It appears that any untranslated strings are blank in Loqui. My guess is that these strings are uploaded to Lokalise as blank to indicate they need translation. However blank (meaning untranslated) isn't checked when downloading these translation files back from Lokalise, leading to this issue. This is a bug with Loqui and a bug report should be made on [its issue tracker](https://github.com/IMB11/Loqui/issues).

**Comment by Gaming32** [comment]
Loqui has fixed this. Here's the message from their Discord:

> @News Pings @Translator Pings 
> 
> # Loqui Empty Strings Fixed
> 
> The bug with empty strings being downloaded has been fixed on the API - it may take 10-20 minutes for my changes to apply globally, after this 10-20 minutes, you should delete your `.loqui_translations` folder in `.minecraft` if you are affected. Thank you for your patience.
> 
> If you're wanting to translate, please help us out here: https://loqui.imb11.dev/
