### ISSUE TITLE
Replace Sodium with Embeddium

### ISSUE THREAD

**Issue by Coccocoahelper** [skywardmc/additive#66]
**Is your request related to a problem? Please describe if so.**

**Describe the mod you'd like to add, remove, or change**
I'd like for Sodium to be replaced with Embeddium, and for Indium to be removed, since it won't be necessary (Embeddium does that anyway). The reason for this is freedom; Sodium no longer protects software freedom, and Embeddium is quite good right now. Reese's Sodium Options can also be removed.

**List alternative mods or solutions you've considered**

**Additional context**

**Comment by uku3lig** [comment]
you know embeddium is for forge right?

_right?_
