### ISSUE TITLE
Add SuperBetterGrass

### ISSUE THREAD

**Issue by ZhaeroGit** [skywardmc/additive#68]
**Is your request related to a problem? Please describe if so.**
There is not really any way to enable better grass, so Im suggesting this.

**Describe the mod you'd like to add, remove, or change**
The mod I want to add SuperBetterGrass Link: https://www.curseforge.com/minecraft/mc-mods/super-better-grass, 

**List alternative mods or solutions you've considered**
There's LambdBetterGrass Link: https://www.curseforge.com/minecraft/mc-mods/lambdabettergrass, however it is only for quilt.

**Additional context**
None

**Comment by notrohit1702** [comment]
> SuperBetterGrass seems nice, however, I am unable to find it on Modrinth.

It's not on Modrinth because LambdaAurora was not fine with it so, after initially being approved it got removed from Modrinth.

**Comment by intergrav** [comment]
Will not be adding since there is no Modrinth version available. However, I'll look into #70 :)
