### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by MadDuck27** [skywardmc/additive#69]
When I go to download the modpack, it downloads as a internet explorer tab and I can't figure out how to get the actual file for the modpack.

**Comment by rowandevving** [comment]
Where are you downloading it from? I don't believe this is an issue with the modpack

**Comment by MadDuck27** [comment]
I’m downloading it directly from modrinth

**Comment by intergrav** [comment]
@MadDuck27 please follow the installation guide to install the modpack :) https://additive.intergrav.xyz/downloads
