### ISSUE TITLE
Add polytone, threadtweak, and noisium to 1.20.6

### ISSUE THREAD

**Issue by Uranite** [skywardmc/additive#71]
**Is your request related to a problem? Please describe if so.**
Those mods are present in other version but not 1.20.6

**Describe the mod you'd like to add, remove, or change**
I'd like polytone, threadtweak, and noisium to be added to additive 1.20.6

**List alternative mods or solutions you've considered**
None

**Additional context**
None

**Comment by intergrav** [comment]
I will next time I update Additive :) last time I updated, the mods weren't available for 1.20.6
