### ISSUE TITLE
add model gap fix?

### ISSUE THREAD

**Issue by nanopone** [skywardmc/additive#73]
**Is your request related to a problem? Please describe if so.**
the tiny sub-pixel gaps between the faces of item models and complex blocks is infinitely infuriating to look at for me

**Describe the mod you'd like to add, remove, or change**
the mod is [model gap fix](https://modrinth.com/mod/modelfix). it has no performance penalty 

**List alternative mods or solutions you've considered**
i would just install it myself, but i figure it would be nice to have it preinstalled and i feel like most people would appreciate it

**Additional context**
fabulously optimised comes with this mod

**Comment by intergrav** [comment]
yea i can add it sometime
