### ISSUE TITLE
1.20.4 quilt does not remember resource packs

### ISSUE THREAD

**Issue by nanopone** [skywardmc/additive#74]
**Describe the bug**
resource pack options do not appear to be saved to options.txt at all. no matter what i do, the array is empty. upon restarting my game, all of the packs have reset. the bug was reproducible in a new instance and on my boyfriends computer.

**To Reproduce**
1. apply a resource pack (or several)
2. restart the game
3. notice that they are no longer applied

**Device info (please complete the following information):**
 - OS: ultramarine kde 40
 - Minecraft version: 1.20.4

**Comment by intergrav** [comment]
It seems like this is an issue with Quilt itself - at least on 1.20.4. I tried in a clean instance with only Quilt and QSL and I was able to reproduce the issue

**Comment by nanopone** [comment]
> It seems like this is an issue with Quilt itself - at least on 1.20.4. I tried in a clean instance with only Quilt and QSL and I was able to reproduce the issue

oh, i didn't think to try quilt alone. i'll play around with different quilt versions and report the bug there. thanks
