### ISSUE TITLE
replace fabrishot with resolutioncontrol++?

### ISSUE THREAD

**Issue by nanopone** [skywardmc/additive#75]
**Is your request related to a problem? Please describe if so.**
i don't have a problem with current versions of fabrishot (since they seem to have fixed the screenshot processing delay in previous versions). i just think resolutioncontrol++ is an improvement because of the other major feature it has

**Describe the mod you'd like to add, remove, or change**
resolutioncontrol++ retains the high resolution screenshot feature of fabrishot, but it also allows the user to supersample or downsample minecraft's render resolution. for weak gpus with high resolution displays (like in modern ultrabooks), this is useful for making the game run at a more reasonable resolution while not compromising the clarity of the hud or the convenience of keeping the same display resolution. for high end machines, it's useful for getting supersample anti-aliasing, as minecraft has no built in anti-aliasing methods. the fullscreen resolution option is also somewhat broken, especially on linux where it doesn't work at all, making resolutioncontrol++ a superior option in my opinion

**Comment by intergrav** [comment]
i dont think i have fabrishot in additive (you may be thinking of Fabulously Optimized, iirc they have it) but i'll look into maybe adding resolutioncontrol++ sometime when im not busy :)

**Comment by nanopone** [comment]
> i dont think i have fabrishot in additive (you may be thinking of Fabulously Optimized, iirc they have it) but i'll look into maybe adding resolutioncontrol++ sometime when im not busy :)

oh damn youre right i think i added it myself and forgot. fabulously optimised has it and i recently switched away from it so thats probably why i was confused
