### ISSUE TITLE
Replace EmuNO with MacOS Input Fixes

### ISSUE THREAD

**Issue by intergrav** [skywardmc/additive#80]
ryan said yes

https://modrinth.com/mod/macos-input-fixes

**Comment by omo50** [comment]
I've heard that the MacOS Input Fixes mod does slightly slow down the game on non Mac systems, so I don't know

I could be wrong, but it is something I have heard going around

**Comment by intergrav** [comment]
honestly from a quick look through the source code i dont see anything that could really reduce performance in any way

**Comment by omo50** [comment]
As I said, it's just something I've heard

I'll probably go ahead and benchmark it myself though just to be sure. It couldn't hurt to check
