### ISSUE TITLE
Mod request for sodium shadowy path blocks to make path blocks look closer to how they look in vanilla or optifine

### ISSUE THREAD

**Issue by Thinkseal** [skywardmc/additive#83]
dirt path's shadows do not look that close to what they look like in vanilla/optifine

sodium shadowy path blocks makes dirt path's shadows look more like how they do in vanilla/optifine

an alternative to this that I have considered is not using this mod and accepting that dirt path's shadows will not look like vanilla's/optifine's dirt path's shadows

vanilla dirt paths shadows
![2024-07-11_21 17 15](https://github.com/user-attachments/assets/31d27a1d-e648-4111-bcf5-23966a586a70)

additive without sodium shadowy path blocks
![2024-07-11_21 11 23](https://github.com/user-attachments/assets/16f54eac-2fce-4a71-8bb6-61f6f560fa50)

additive with sodium shadowy path blocks
![2024-07-11_21 12 22](https://github.com/user-attachments/assets/6cd6491e-6193-4f70-bf35-d5272b3a55e6)

link to the mod: [https://modrinth.com/mod/sodium-shadowy-path-blocks](https://modrinth.com/mod/sodium-shadowy-path-blocks)

**Comment by intergrav** [comment]
I think the current path blocks look fine and I don't really want to rely on another Sodium addon as there are so many in the list already. Feel free to add it manually though.

**Comment by Thinkseal** [comment]
ok cool
